### ISSUE TITLE
変数名はもうちょっと工夫したほうがいいと思う

### ISSUE THREAD

**Issue by c0b2103990** [8170/ProjExD#2]
https://github.com/8170/ProjExD/blob/c00d255230311d4e11527d6938b9c84350bb4910/ex01/alphabet.py#L5

**Comment by 8170** [comment]
申し訳ございません、私はこのスタンスになじんでいますので、グループワークであることを忘れておりました。次回以降は見やすいような変数名を使用することを心がけます。
